version: '3.9'


services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  #redis:
  #  image: "redis:alpine"
  #  #command: redis-server --requirepass password
  # command: redis-server
  #  ports:
  #    - "6379:6379"
